/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHistory;
import Model.Application;
import Model.Database;
import Model.Kereta;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class historyframe extends javax.swing.JFrame {
    
    ControllerHistory ck = new ControllerHistory();
    /**
     * Creates new form historyframe
     */
    //Application app;
    Connection conn;
    Statement stmt;
    ResultSet rs;
    public historyframe() {
        //app = a;
        
        initComponents();
        //ck.loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        transaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kembalimenuawal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(null);

        transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaksi ID", "No KTP", "Nama Kereta", "Keberangkatan", "Tujuan", "Jumlah Tiket", "No Kursi", "Harga Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transaksi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 280, 920, 320);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  MENU RIWAYAT PEMBELIAN TIKET");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 6, 6, 6, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 40, 470, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NO KTP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 220, 60, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("masukan data anda");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 160, 190, 40);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari);
        btnCari.setBounds(460, 220, 80, 30);

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari);
        cari.setBounds(190, 220, 250, 30);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 20, 470, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aassss.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 160, 460, 110);

        kembalimenuawal.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        kembalimenuawal.setText("kembali");
        kembalimenuawal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembalimenuawalMouseClicked(evt);
            }
        });
        kembalimenuawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalimenuawalActionPerformed(evt);
            }
        });
        getContentPane().add(kembalimenuawal);
        kembalimenuawal.setBounds(890, 210, 140, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/popo.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 1210, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void kembalimenuawalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembalimenuawalMouseClicked
        // TODO add your handling code here:
        menuutama A = new menuutama();
        A.setVisible(true);
        A.pack();
        A.setSize(1180, 660);
        A.setLocationRelativeTo(null);
        A.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_kembalimenuawalMouseClicked

    private void kembalimenuawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalimenuawalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalimenuawalActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        //ck.cariTransaksi(cari.getText().toString());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Transaksi ID", "No KTP", "Nama Kereta", 
                    "Keberangkatan", "Tujuan", "Jumlah Tiket",
                    "No Kursi", "Harga Total"});
        Object[] row = new Object[8];
        
        Database db = new Database();
        connect();
        String query = "SELECT * FROM transaksi WHERE noKTP = '" + cari.getText().toString() + "';";
        try {
            rs = stmt.executeQuery(query);
            while (rs.next()) {
                Kereta kereta = db.cariKereta(rs.getString("keretaID").toString());           
                row[0] = rs.getString("transaksiID");
                row[1] = rs.getString("noKTP");
                row[2] = rs.getString("keretaID");
                row[3] = rs.getString("keberangkatan");
                row[4] = rs.getString("tujuan");
                row[5] = rs.getInt("jmlhPesan");
                row[6] = rs.getString("noKursi");
                row[7] = rs.getDouble("total");
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("wah");
        }
        transaksi.setModel(model);
        disconnect();
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historyframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new historyframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembalimenuawal;
    private javax.swing.JTable transaksi;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ControllerHistory aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setTransaksi(DefaultTableModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public String getCari() {
        return cari.getText();
    }

    public JTable getTransaksi() {
        return transaksi;
    }

    public JButton getKembalimenuawal() {
        return kembalimenuawal;
    }

    private void connect() {
        String url = "jdbc:mysql://localhost/pemesanan_tiket";
        String user = "root";
        String pass = "";
        try {
            conn = DriverManager.getConnection(url, user, pass);
            stmt = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void disconnect() {
         try {
            conn.close();
            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
